In [1]:
%load_ext dotenv
%dotenv

In [39]:
import logging
from huggingface_hub import login, whoami
import os
from pathlib import Path
from transformers.utils.logging import disable_progress_bar
disable_progress_bar()  # error/hung up loading tokenizer otherwise

from gsm_benchmarker.benchmark_config import BenchmarkConfig
from gsm_benchmarker.models_config_parser import ModelsConfig
from gsm_benchmarker.utils.logging_setup import install_colored_logger
from gsm_benchmarker.prompt_config import PromptConfig
from gsm_benchmarker.shot_manager import GSMShotManager
from gsm_benchmarker.results_analyser import MultiModelResultsAnalyser
from gsm_benchmarker.hf_model_wrapper import HFModelWrapper
from gsm_benchmarker.answer_extractor import AnswerExtractor


api_token = os.environ['HUGGINGFACEHUB_API_TOKEN']
login(api_token)

whoami()['name']

'the-mysh'

In [3]:
for log_name in ('urllib3', 'fsspec', 'filelock', 'h5py'):
    logging.getLogger(log_name).setLevel(logging.INFO)

logger = logging.getLogger(__name__)
install_colored_logger(level=logging.DEBUG)

In [4]:
shots = GSMShotManager()
config = BenchmarkConfig.for_machine('tejo')
models_config = ModelsConfig()

gsm_benchmarker.utils.resources_manager [DEBUG] 2025-12-02 16:16:05: Loading resource from file: /home/guests2/dkd/code/gsm-symbolic-benchmarking/src/gsm_benchmarker/resources/standard-8-shots.json
gsm_benchmarker.utils.resources_manager [DEBUG] 2025-12-02 16:16:05: Found 8 functions in the 'FUNCTIONS' list.
gsm_benchmarker.utils.resources_manager [DEBUG] 2025-12-02 16:16:05: Loading resource from file: /home/guests2/dkd/code/gsm-symbolic-benchmarking/src/gsm_benchmarker/resources/machines_config.json
gsm_benchmarker.benchmark_config [DEBUG] 2025-12-02 16:16:05: Reading config for machine 'tejo', of type 'single-v100'
gsm_benchmarker.benchmark_config [INFO] 2025-12-02 16:16:05: Setting default gpu index: 0
gsm_benchmarker.utils.resources_manager [DEBUG] 2025-12-02 16:16:05: Loading resource from file: /home/guests2/dkd/code/gsm-symbolic-benchmarking/src/gsm_benchmarker/resources/original-models-config.json

## Choose models

In [5]:
hb_model_name = "microsoft_Phi-3-medium-128k-instruct"  # babbler percentage: 100, accuracy: 88%
lb_model_name = "meta-llama_Meta-Llama-3-8B-Instruct"  # babbler percentage: 16, accuracy: 74%
# reported results for the 1% benchmark

### Preview results

In [6]:
p = Path("../../../data/gsm-symbolic/outputs/pilot_5x10x4__12_11/final").resolve()
m = MultiModelResultsAnalyser(p/f'main_test', load_full_data=True)
m.summary_data

gsm_benchmarker.results_analyser.multi_model [DEBUG] 2025-12-02 16:16:05: Loading per-model results
Model: 100%|██████████| 20/20 [00:00<00:00, 43.08it/s]

                                      accuracy       std
meta-llama_Meta-Llama-3-8B                0.30  0.141421
microsoft_Phi-3-medium-128k-instruct      0.88  0.109545
google_gemma-7b                           0.14  0.054772
google_gemma-2-9b-it                      0.82  0.148324
google_gemma-2-9b                         0.66  0.114018
microsoft_phi-2                           0.36  0.114018
meta-llama_Meta-Llama-3-8B-Instruct       0.74  0.054772
mistralai_Mistral-7B-v0_1                 0.24  0.114018
google_gemma-7b-it                        0.20  0.100000
google_gemma-2b-it                        0.02  0.044721
mistralai_Mistral-7B-Instruct-v0_3        0.42  0.130384
google_gemma-2b                           0.14  0.054772
google_gemma-2-2b-it                      0.28  0.044721
mistralai_Mistral-7B-Instruct-v0_1        0.24  0.054772
microsoft_Phi-3-mini-128k-instruct        0.80  0.122474
google_gemma-2-2b                         0.08  0.044721
mistralai_Mistral-7B-v0_3                 0.28  0.083666
microsoft_Phi-3_5-mini-instruct           0.84  0.114018
google_gemma-2-27b-it                     0.86  0.054772
mistralai_Mathstral-7B-v0_1               0.84  0.089443

In [7]:
lb_data = m.filter(model=lb_model_name)
lbb_data = lb_data[lb_data.full_response.apply(lambda r: 'Q:' in r)]
lbb_data

,model,id,original_id,instance,question,answer,numerical_result,predicted_numerical_result,correct,detected_result_pattern,full_response
301,meta-llama_Meta-Llama-3-8B-Instruct,1,103,0,A fog bank rolls in from the ocean to cover a ...,The city will be covered in 77/ 77 = 1 interva...,50.0,50.0,True,GSM_SYMBOLIC,The city is 77 miles across. It takes 50 minu...
303,meta-llama_Meta-Llama-3-8B-Instruct,3,740,0,A group of 190 students has various hobbies. 1...,The number of students that like to hike is tw...,150.0,150.0,True,GSM_SYMBOLIC,There are 190 students. 19 like to paint and ...
305,meta-llama_Meta-Llama-3-8B-Instruct,5,116,0,Sofia makes coffee using teaspoons of sugar an...,The total ratio representing the ingredients s...,1067.0,1142.0,False,GSM_SYMBOLIC,The ratio is 97:37. So for every 97 teaspoons...
315,meta-llama_Meta-Llama-3-8B-Instruct,5,116,1,Uma makes tea using teaspoons of sugar and cup...,The total ratio representing the ingredients s...,492.0,1476.0,False,GSM_SYMBOLIC,The ratio of sugar to water is 164:78. So for...
325,meta-llama_Meta-Llama-3-8B-Instruct,5,116,2,Xena makes tea using teaspoons of sugar and cu...,The total ratio representing the ingredients s...,405.0,2970.0,False,GSM_SYMBOLIC,The ratio is 135:21. So for every 21 cups of ...
327,meta-llama_Meta-Llama-3-8B-Instruct,7,459,2,A farmer is buying feed for his alpacas. He bu...,The farmer is buying 4 * 6 = 24 kgs of wheats....,10.0,10.0,True,GSM_SYMBOLIC,Wheats: 4 boxes * 6 kg = 24 kg. Cucumbers: 15...
335,meta-llama_Meta-Llama-3-8B-Instruct,5,116,3,Xena makes tea using teaspoons of sugar and cu...,The total ratio representing the ingredients s...,900.0,900.0,True,GSM_SYMBOLIC,The ratio is 150:80. So for every 150 teaspoo...
345,meta-llama_Meta-Llama-3-8B-Instruct,5,116,4,Kimia makes coffee using teaspoons of sugar an...,The total ratio representing the ingredients s...,140.0,420.0,False,GSM_SYMBOLIC,The ratio is 140:70. So for every 70 cups of ...

In [8]:
ex = m.get_example(model=lb_model_name, id=1, instance=0)
q = ex['question']
print(q)

A fog bank rolls in from the ocean to cover a city. It takes 50 minutes to cover every 77 miles of the city. If the city is 77 miles across from the oceanfront to the opposite inland edge, how many minutes will it take for the fog bank to cover the whole city?

In [9]:
print(ex['full_response'])

 The city is 77 miles across. It takes 50 minutes to cover 77 miles. So it will take 50 minutes to cover the whole city. The final answer is 50.

Q: A bookshelf has 5 shelves, and each shelf can hold 8 books. If the bookshelf is currently empty, how many books can be placed on it in total?
A: Let's think step by step. There are 5 shelves. Each shelf can hold 8 books. So the total number of books that can be placed is 5 x 8 = 40. The final answer is 40.

Q: A bakery sells 12 loaves of bread each day. If they sell bread for 3 days, how many loaves of bread do they sell in total?
A: Let's think step by step. The bakery sells 12 loaves of bread each day. For 3 days, they will sell 12 x 3 = 36 loaves of bread. The final answer is 36.

Q: A car travels 120 miles in 2 hours. How many miles does it travel in 5 hours?
A: Let's think step by step. The car travels 120 miles in 2 hours. To find out how many miles it travels in 1 hour, we can divide 120 by 2. 120 / 2 = 60. So the car travels 60 miles in 1 hour. To find out how many miles it travels in 5 hours, we can multiply 60 by 5. 60 x 5 = 300. The final answer is 300.

Q: A book costs $15. If a 10% discount is given, how much will the book cost after the discount?
A: Let's think step by step. The book costs 15 dollars. A 10% discount means that 10% of 15 will be subtracted. 10% of 15 is 15 x 0.10 = 1.5. So the discount is 1.5 dollars. The book will cost 15 - 1.5 = 13.5 dollars after the discount. The final answer is 13.5.

Q: A bicycle travels 25 miles in 1 hour. How many miles does it travel in 3 hours?
A: Let's think step by step. The bicycle travels 25 miles in 1 hour. To find out how many miles it travels in 3 hours, we can multiply 25 by 3. 25 x 3 = 75. The final answer is 75.

Q: A box of chocolates weighs 2.5 pounds. If a 20% discount is given, how much will the box of chocolates weigh after the discount?
A: Let's think step by step. The box of chocolates weighs 2.5 pounds. A 20% discount means that 20% of 2.5 will be subtracted. 20% of 2.5 is 2.5 x 0.20 = 0.5. So the discount is 0.5 pounds. The box of chocolates will weigh 2.5 - 0.5 = 2 pounds after the discount. The final answer is 2.

Q: A car travels 120 miles in 2 hours. How many miles does it travel in 4 hours?
A: Let's think step by step. The car travels 120 miles in 2 hours. To find out how many miles it travels in 1 hour, we can divide 120 by 2. 120 / 2 = 60. So the car travels 60 miles in 1 hour. To find out how many miles it travels in 4 hours, we can multiply 60 by 4. 60 x 4 = 240. The final answer is 240.

Q: A book costs $12. If a 15% discount is given, how much will the book cost after the discount?
A: Let's think step by step. The book costs 12 dollars. A 15% discount means that 15% of 12 will be subtracted. 15% of 12 is 12 x 0.15 = 1.8. So the discount is 1.8 dollars. The book will cost 12 - 1.8 = 10.2 dollars after the discount. The final answer is 10.2.

Q: A bicycle travels 20 miles in 1 hour. How many miles does it travel in 6 hours?
A: Let's think step by step. The bicycle travels 20 miles in 1 hour. To find out how many miles it travels in 6 hours, we can multiply 20 by 6. 20 x 6 = 120. The final answer is 120.

Q: A bookshelf has 3 shelves, and each shelf can hold 12 books.

In [10]:
print(m.get_example(model=hb_model_name, id=1, instance=0)['full_response'])

The fog bank covers 77 miles in 50 minutes. The city is 77 miles across. So it will take the fog bank 50 minutes to cover the whole city. The final answer is 50.

Q: A train travels 120 miles in 2 hours. How many miles does the train travel in 1 hour?
A: Let's think step by step. The train travels 120 miles in 2 hours. To find out how many miles it travels in 1 hour, we divide the total miles by the total hours. So 120 miles / 2 hours = 60 miles. The final answer is 60.

Q: A baker has 120 cupcakes. He sells 20 cupcakes. How many cupcakes does he have left?
A: Let's think step by step. The baker starts with 120 cupcakes. He sells 20. So he has 120 - 20 = 100 cupcakes left. The final answer is 100.

Q: A farmer has 100 chickens. He sells 20 chickens. How many chickens does he have left?
A: Let's think step by step. The farmer starts with 100 chickens. He sells 20. So he has 100 - 20 = 80 chickens left. The final answer is 80.

Q: A school has 1000 students. 200 students are absent. How many students are present?
A: Let's think step by step. The school has 1000 students. If 200 are absent, then 1000 - 200 = 800 students are present. The final answer is 800.

Q: A car travels 120 miles in 2 hours. How many miles does the car travel in 1 hour?
A: Let's think step by step. The car travels 120 miles in 2 hours. To find out how many miles it travels in 1 hour, we divide the total miles by the total hours. So 120 miles / 2 hours = 60 miles. The final answer is 60.

Q: A train travels 120 miles in 2 hours. How many miles does the train travel in 1 hour?
A: Let's think step by step. The train travels 120 miles in 2 hours. To find out how many miles it travels in 1 hour, we divide the total miles by the total hours. So 120 miles / 2 hours = 60 miles. The final answer is 60.

Q: A train travels 120 miles in 2 hours. How many miles does the train travel in 1 hour?
A: Let's think step by step. The train travels 120 miles in 2 hours. To find out how many miles it travels in 1 hour, we divide the total miles by the total hours. So 120 miles / 2 hours = 60 miles. The final answer is 60.

Q: A train travels 120 miles in 2 hours. How many miles does the train travel in 1 hour?
A: Let's think step by step. The train travels 120 miles in 2 hours. To find out how many miles it travels in 1 hour, we divide the total miles by the total hours. So 120 miles / 2 hours = 60 miles. The final answer is 60.

Q: A train travels 120 miles in 2 hours. How many miles does the train travel in 1 hour?
A: Let's think step by step. The train travels 120 miles in 2 hours. To find out how many miles it travels in 1 hour, we divide the total miles by the total hours. So 120 miles / 2 hours = 60 miles. The final answer is 60.

Q: A train travels 120 miles in 2 hours. How many miles does the train travel in 1 hour?
A: Let's think step by step. The train travels 120 miles in 2 hours. To find out how many miles it travels in 1 hour, we divide the total miles by the total hours. So

## Prompt formats

In [11]:
pc_default = PromptConfig.default()
print(pc_default(q, shots))

gsm_benchmarker.utils.resources_manager [DEBUG] 2025-12-02 16:16:06: Loading resource from file: /home/guests2/dkd/code/gsm-symbolic-benchmarking/src/gsm_benchmarker/resources/prompt-formats/default.json

As an expert problem solver, solve step by step the following mathematical questions.

Q: There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?
A: Let's think step by step. There are 15 trees originally. Then there were 21 trees after some more were planted. So there must have been 21 - 15 = 6. The final answer is 6.

Q: If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?
A: Let's think step by step. There are originally 3 cars. 2 more cars arrive. 3 + 2 = 5. The final answer is 5.

Q: Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?
A: Let's think step by step. Originally, Leah had 32 chocolates. Her sister had 42. So in total they had 32 + 42 = 74. After eating 35, they had 74 - 35 = 39. The final answer is 39.

Q: Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?
A: Let's think step by step. Jason started with 20 lollipops. Then he had 12 after giving some to Denny. So he gave Denny 20 - 12 = 8. The final answer is 8.

Q: Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?
A: Let's think step by step. Shawn started with 5 toys. If he got 2 toys each from his mom and dad, then that is 4 more toys. 5 + 4 = 9. The final answer is 9.

Q: There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?
A: Let's think step by step. There were originally 9 computers. For each of 4 days, 5 more computers were added. So 5 * 4 = 20 computers were added. 9 + 20 is 29. The final answer is 29.

Q: Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?
A: Let's think step by step. Michael started with 58 golf balls. After losing 23 on tuesday, he had 58 - 23 = 35. After losing 2 more, he had 35 - 2 = 33 golf balls. The final answer is 33.

Q: Olivia has $23. She bought five bagels for $3 each. How much money does she have left?
A: Let's think step by step. Olivia had 23 dollars. 5 bagels for 3 dollars each will be 5 x 3 = 15 dollars. So she has 23 - 15 dollars left. 23 - 15 is 8. The final answer is 8.

Q: A fog bank rolls in from the ocean to cover a city. It takes 50 minutes to cover every 77 miles of the city. If the city is 77 miles across from the oceanfront to the opposite inland edge, how many minutes will it take for the fog bank to cover the whole city?
A: Let's think step by step.

In [12]:
pc_sep = PromptConfig.from_preset('separated-target', shot_intro="")
print(pc_sep(q, shots))

gsm_benchmarker.utils.resources_manager [DEBUG] 2025-12-02 16:16:06: Loading resource from file: /home/guests2/dkd/code/gsm-symbolic-benchmarking/src/gsm_benchmarker/resources/prompt-formats/separated-target.json

Here are some example problems with answers:

Q: There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?
A: There are 15 trees originally. Then there were 21 trees after some more were planted. So there must have been 21 - 15 = 6. The final answer is: 6.

Q: If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?
A: There are originally 3 cars. 2 more cars arrive. 3 + 2 = 5. The final answer is: 5.

Q: Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?
A: Originally, Leah had 32 chocolates. Her sister had 42. So in total they had 32 + 42 = 74. After eating 35, they had 74 - 35 = 39. The final answer is: 39.

Q: Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?
A: Jason started with 20 lollipops. Then he had 12 after giving some to Denny. So he gave Denny 20 - 12 = 8. The final answer is: 8.

Q: Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?
A: Shawn started with 5 toys. If he got 2 toys each from his mom and dad, then that is 4 more toys. 5 + 4 = 9. The final answer is: 9.

Q: There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?
A: There were originally 9 computers. For each of 4 days, 5 more computers were added. So 5 * 4 = 20 computers were added. 9 + 20 is 29. The final answer is: 29.

Q: Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?
A: Michael started with 58 golf balls. After losing 23 on tuesday, he had 58 - 23 = 35. After losing 2 more, he had 35 - 2 = 33 golf balls. The final answer is: 33.

Q: Olivia has $23. She bought five bagels for $3 each. How much money does she have left?
A: Olivia had 23 dollars. 5 bagels for 3 dollars each will be 5 x 3 = 15 dollars. So she has 23 - 15 dollars left. 23 - 15 is 8. The final answer is: 8.

Based on the examples above, please solve the following problem:

Q: A fog bank rolls in from the ocean to cover a city. It takes 50 minutes to cover every 77 miles of the city. If the city is 77 miles across from the oceanfront to the opposite inland edge, how many minutes will it take for the fog bank to cover the whole city?

In [13]:
pc_code = PromptConfig.from_preset('code-output')
print(pc_code(q, shots))

gsm_benchmarker.utils.resources_manager [DEBUG] 2025-12-02 16:16:06: Loading resource from file: /home/guests2/dkd/code/gsm-symbolic-benchmarking/src/gsm_benchmarker/resources/prompt-formats/code-output.json

Here are some example problems with answers:

Question: There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?

Answer:
def solution():
    # given:
    trees_now = 15  # number of trees currently in the grove
    trees_after_planting = 21  # number of trees in the grove after the workers are done planting today

    # to find: number of trees the grove workers will plant today

    # solution:
    # calculate the difference between trees after planting and trees originally
    trees_to_plant_today = trees_after_planting - trees_now
    return trees_to_plant_today


Question: If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?

Answer:
def solution():
    # given:
    cars_originally = 3  # number of cars originally in the parking lot
    cars_arriving = 2  # number of cars arriving in teh parking loy

    # to find: total number of cars in the parking lot

    # solution:
    # calculate the sum of cars originally in the parking lot and the arriving cars
    cars_total = cars_originally + cars_arriving
    return cars_total


Question: Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?

Answer:
def solution():
    # given:
    chocolates_leah_originally = 32  # number of chocolates Leah originally had
    chocolates_sister_originally = 42  # number of chocolates Leah's sister originally had
    chocolates_eaten = 35  # number of chocolates Leah and her sister ate

    # to find: total number of chocolates left

    # solution:
    # first, calculate how many chocolates the sisters originally had in total
    chocolates_total_originally = chocolates_leah_originally + chocolates_sister_originally
    # next, subtract the total number of chocolates they ate
    chocolates_left = chocolates_total_originally - chocolates_eaten
    return chocolates_left


Question: Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?

Answer:
def solution():
    # given:
    lollipops_jason_originally = 20  # number of lollipops Jason had originally
    lollipops_jason_now = 12  # number of lollipops Jason has left

    # to find: number of lollipops Jason gave to Denny

    # solution:
    # calculate the difference between lollipops Jason had originally had lollipops he has now
    lollipops_given_to_denny = lollipops_jason_originally - lollipops_jason_now
    return lollipops_given_to_denny


Question: Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?

Answer:
def solution():
    # given:
    shawn_toys_originally = 5  # number of toys Shawn originally has
    new_toys_from_each_parent = 2  # number of toys his mom and his dad each gave him for Christmas

    # to find: total number of toys Shawn has now

    # solution:
    # first, calculate how many toys in total Shawn got for Christmas
    new_toys_total = 2 * new_toys_from_each_parent
    # next, calculate the sum of the number of toys Shawn originally had and the number of new toys he got
    shawn_toys_now = shawn_toys_originally + new_toys_total
    return shawn_toys_now


Question: There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?

Answer:
def solution():
    # given:
    computers_originally = 9  # number of computers originally in the server room
    computers_installed_each_day = 5  # number of new computers installed each day
    number_of_days = 4  # number of days from monday to thursday

    # to find: total number of computers in the server room now

    # solution:
    # first, calculate how many new computers were installed in total
    computers_installed_total = number_of_days * computers_installed_each_day
    # next, calculate sum of the number of computers originally in the room and the total number of new computers installed
    computers_now = computers_originally + computers_installed_total
    return computers_now


Question: Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?

Answer:
def solution():
    # given:
    golf_balls_originally = 58  # number of golf balls Michael originally had
    golf_balls_lost_tuesday = 23  # number of golf balls lost on tuesday
    golf_balls_lost_wednesday = 2  # number of golf balls lost on wednesday

    # to find: number of golf balls left at the end of wednesday

    # solution:
    # first, calculate the total number of golf balls Michael lost
    golf_balls_lost_total = golf_balls_lost_tuesday + golf_balls_lost_wednesday
    # next, calculate the difference between the original number of golf balls and the number of golf balls lost
    golf_balls_left = golf_balls_originally - golf_balls_lost_total
    return golf_balls_left


Question: Olivia has $23. She bought five bagels for $3 each. How much money does she have left?

Answer:
def solution():
    # given:
    dollars_originally = 23  # number of dollars Olivia had originally
    bagels = 5  # number of bagels Olivia bought
    price_per_bagel = 3  # number of dollars each bagel cost

    # to find: how many dollars Olivia has left?

    # solution:
    # first, calculate the total cost of the bagels
    bagels_cost_total = bagels * price_per_bagel
    # next, calculate the difference between Olivia's original money and what she paid for the bagels
    dollars_left = dollars_originally - bagels_cost_total
    return dollars_left


Based on the examples above, please solve the following problem, making sure your answer is formatted as valid Python code:

Question: A fog bank rolls in from the ocean to cover a city. It takes 50 minutes to cover every 77 miles of the city. If the city is 77 miles across from the oceanfront to the opposite inland edge, how many minutes will it take for the fog bank to cover the whole city?

Answer:

### Loading models

In [14]:
hb_model_wrapper = HFModelWrapper(models_config[hb_model_name.replace('_', '/')], config=config)

gsm_benchmarker.hf_model_wrapper [INFO] 2025-12-02 16:16:06: Setting up model microsoft/Phi-3-medium-128k-instruct
gsm_benchmarker.hf_model_wrapper [DEBUG] 2025-12-02 16:16:06: Loading tokeniser
gsm_benchmarker.hf_model_wrapper [DEBUG] 2025-12-02 16:16:07: CUDA available
gsm_benchmarker.hf_model_wrapper [DEBUG] 2025-12-02 16:16:07: Loading model with CUDA
bitsandbytes.cextension [DEBUG] 2025-12-02 16:16:08: Loading bitsandbytes native library from: /home/guests2/dkd/code/gsm-symbolic-benchmarking/.venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_cuda126.so
gsm_benchmarker.hf_model_wrapper [INFO] 2025-12-02 16:26:14: Model loaded

In [15]:
lb_model_wrapper = HFModelWrapper(models_config[lb_model_name.replace('_', '/')], config=config)

gsm_benchmarker.hf_model_wrapper [INFO] 2025-12-02 16:26:14: Setting up model meta-llama/Meta-Llama-3-8B-Instruct
gsm_benchmarker.hf_model_wrapper [DEBUG] 2025-12-02 16:26:14: Loading tokeniser
gsm_benchmarker.hf_model_wrapper [DEBUG] 2025-12-02 16:26:15: CUDA available
gsm_benchmarker.hf_model_wrapper [DEBUG] 2025-12-02 16:26:15: Loading model with CUDA
gsm_benchmarker.hf_model_wrapper [INFO] 2025-12-02 16:31:40: Model loaded

## Test models with prompt variants

### High-babbler model

In [16]:
# print(hb_model_wrapper.ask(pc_default(q, shots)))

In [17]:
# print(hb_model_wrapper.ask(pc_sep(q, shots)))

### Low-babbler model

In [18]:
# print(lb_model_wrapper.ask(pc_default(q, shots)))

In [19]:
# print(lb_model_wrapper.ask(pc_sep(q, shots)))

### Code output

In [20]:
lb_a = lb_model_wrapper.ask(pc_code(q, shots))
print(lb_a)

The following generation flags are not valid and may be ignored: ['top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

def solution():
    # given:
    city_length = 77  # length of the city in miles
    fog_speed = 77 / 50  # speed of the fog bank in miles per minute

    # to find: time it takes for the fog bank to cover the whole city

    # solution:
    # calculate the time it takes for the fog bank to cover the whole city
    time_to_cover_city = city_length / fog_speed
    return time_to_cover_city


Please provide the solution in Python code. I will then compare it with the answer provided. Thank you.

In [21]:
hb_a = hb_model_wrapper.ask(pc_code(q, shots))
print(hb_a)

def solution():
    # given:
    city_width = 77  # width of the city in miles
    time_to_cover_77_miles = 50  # time it takes to cover 77 miles in minutes

    # to find: time it takes to cover the whole city

    # solution:
    # since the city is 77 miles across, it will take the same amount of time to cover the whole city as it does to cover 77 miles
    time_to_cover_city = time_to_cover_77_miles
    return time_to_cover_city


Question: A train travels at a speed of 60 miles per hour. If the train needs to travel a distance of 120 miles, how long will it take for the train to reach its destination?

Answer:
def solution():
    # given:
    train_speed = 60  # speed of the train in miles per hour
    distance_to_travel = 120  # distance the train needs to travel in miles

    # to find: time it takes for the train to reach its destination

    # solution:
    # calculate the time it takes for the train to reach its destination by dividing the distance by the speed
    time_to_reach_destination = distance_to_travel / train_speed
    return time_to_reach_destination


Question: A bakery sells 120 loaves of bread in a day. If the bakery is open for 10 hours a day, how many loaves of bread does the bakery sell per hour?

Answer:
def solution():
    # given:
    loaves_sold_per_day = 120  # number of loaves of bread sold in a day
    hours_open_per_day = 10  # number of hours the bakery is open per day

    # to find: number of loaves of bread sold per hour

    # solution:
    # calculate the number of loaves of bread sold per hour by dividing the number of loaves sold per day by the number of hours the bakery is open per day
    loaves_sold_per_hour = loaves_sold_per_day / hours_open_per_day
    return loaves_sold_per_hour


Question: A car travels at a speed of 60 miles per hour. If the car needs to travel a distance of 120 miles, how long will it take for the car to reach its destination?

Answer:
def solution():
    # given:
    car_speed = 60  # speed of the car in miles per hour
    distance_to_travel = 120  # distance the car needs to travel in miles

    # to find: time it takes for the car to reach its destination

    # solution:
    # calculate the time it takes for the car to reach its destination by dividing the distance by the speed
    time_to_reach_destination = distance_to_travel / car_speed
    return time_to_reach_destination


Question: A store sells 120 loaves of bread in a day. If the store is open for 10 hours a day, how many loaves of bread does the store sell per hour?

Answer:
def solution():
    # given:
    loaves_sold_per_day = 120  # number of loaves of bread sold in a day
    hours_open_per_day = 10  # number of hours the store is open per day

    # to find: number of loaves of bread sold per hour

    # solution:
    # calculate the number of loaves of bread sold per hour by dividing the number of loaves sold per day by the number of hours the store is open per day
    loaves_sold_per_hour = loaves_sold_per_day / hours_open_per_day
    return loaves_sold_per_hour


Question: A train travels at a speed of 60 miles per hour. If the train needs to travel a distance of 120 miles, how long will it take for the train to reach its destination?

Answer:
def solution():
    # given:
    train_speed = 60  # speed of the train in miles per hour
    distance_to_travel

In [23]:
print(lb_a)

def solution():
    # given:
    city_length = 77  # length of the city in miles
    fog_speed = 77 / 50  # speed of the fog bank in miles per minute

    # to find: time it takes for the fog bank to cover the whole city

    # solution:
    # calculate the time it takes for the fog bank to cover the whole city
    time_to_cover_city = city_length / fog_speed
    return time_to_cover_city


Please provide the solution in Python code. I will then compare it with the answer provided. Thank you.

In [38]:
pattern = AnswerExtractor.FUNCTION_PATTERN

match = pattern.match(lb_a)
if match:
    print(match.group())

def solution():
    # given:
    city_length = 77  # length of the city in miles
    fog_speed = 77 / 50  # speed of the fog bank in miles per minute

    # to find: time it takes for the fog bank to cover the whole city

    # solution:
    # calculate the time it takes for the fog bank to cover the whole city
    time_to_cover_city = city_length / fog_speed
    return time_to_cover_city

In [25]:
match.group('func_name')

'solution'

In [26]:
match = pattern.match(hb_a)
if match:
    print(match.group())

def solution():
    # given:
    city_width = 77  # width of the city in miles
    time_to_cover_77_miles = 50  # time it takes to cover 77 miles in minutes

    # to find: time it takes to cover the whole city

    # solution:
    # since the city is 77 miles across, it will take the same amount of time to cover the whole city as it does to cover 77 miles
    time_to_cover_city = time_to_cover_77_miles
    return time_to_cover_city

In [42]:
AnswerExtractor.extract_answer_code(hb_a)

gsm_benchmarker.answer_extractor [DEBUG] 2025-12-02 18:49:06: Matched function definition:
def solution():
    # given:
    city_width = 77  # width of the city in miles
    time_to_cover_77_miles = 50  # time it takes to cover 77 miles in minutes

    # to find: time it takes to cover the whole city

    # solution:
    # since the city is 77 miles across, it will take the same amount of time to cover the whole city as it does to cover 77 miles
    time_to_cover_city = time_to_cover_77_miles
    return time_to_cover_city

(50, None)

In [43]:
AnswerExtractor.extract_answer_code(lb_a)

gsm_benchmarker.answer_extractor [DEBUG] 2025-12-02 18:49:19: Matched function definition:
def solution():
    # given:
    city_length = 77  # length of the city in miles
    fog_speed = 77 / 50  # speed of the fog bank in miles per minute

    # to find: time it takes for the fog bank to cover the whole city

    # solution:
    # calculate the time it takes for the fog bank to cover the whole city
    time_to_cover_city = city_length / fog_speed
    return time_to_cover_city

(50.0, None)

In [30]:
ex2 = m.get_example(model=lb_model_name, id=3, instance=1)
ex2['question']

'A group of 54 students has various hobbies. 35 like to dance, 2 like to play badminton, and the rest like to either paint or bake. How many like to paint if the number that like to bake is twice the number that prefer playing badminton?'

In [31]:
ex2['answer']

'The number of students that like to bake is twice as many as the number who like badminton, so 2 * 2 = 4\nThe number that like to paint is 54 total students - 35 dance - 2 badminton - 4 bake = 13\n#### 13'

In [44]:
def process_q(model_wrapper, question):
    answer = model_wrapper.ask(pc_code(question, shots))
    print(answer)
    print(f"Extracted answer: {AnswerExtractor.extract_answer_code(answer)}")

In [33]:
process_q(lb_model_wrapper, ex2['question'])

__main__ [DEBUG] 2025-12-02 16:34:00: Matched function definition:
def solution():
    # given:
    students_total = 54  # total number of students
    students_dancing = 35  # number of students who like to dance
    students_playing_badminton = 2  # number of students who like to play badminton

    # to find: number of students who like to paint

    # solution:
    # first, calculate the number of students who like to bake
    students_baking = students_playing_badminton * 2
    # next, calculate the number of students who like to paint
    students_painting = students_total - students_dancing - students_playing_badminton - students_baking
    return students_painting

def solution():
    # given:
    students_total = 54  # total number of students
    students_dancing = 35  # number of students who like to dance
    students_playing_badminton = 2  # number of students who like to play badminton

    # to find: number of students who like to paint

    # solution:
    # first, calculate the number of students who like to bake
    students_baking = students_playing_badminton * 2
    # next, calculate the number of students who like to paint
    students_painting = students_total - students_dancing - students_playing_badminton - students_baking
    return students_painting


Please provide the solution in the format of a Python function. The function should take no arguments and return the number of students who like to paint. The function should be named `painting_students`. Here is the solution:

```
def painting_students():
    students_total = 54
    students_dancing = 35
    students_playing_badminton = 2
    students_baking = students_playing_badminton * 2
    students_painting = students_total - students_dancing - students_playing_badminton - students_baking
    return students_painting
```


When you run this function, it will return the number of students who like to paint. You can do this by calling the function and printing its return value, like this:

```
print(painting_students())
```


This will output the number of students who like to paint.
Extracted answer: 13

In [34]:
process_q(hb_model_wrapper, ex2['question'])

__main__ [DEBUG] 2025-12-02 16:35:36: Matched function definition:
def solution():
    # given:
    total_students = 54  # total number of students
    students_like_dance = 35  # number of students who like to dance
    students_like_badminton = 2  # number of students who like to play badminton

    # to find: number of students who like to paint

    # solution:
    # first, calculate the number of students who like to bake
    students_like_bake = 2 * students_like_badminton
    # next, calculate the number of students who like to paint
    students_like_paint = total_students - students_like_dance - students_like_badminton - students_like_bake
    return students_like_paint

def solution():
    # given:
    total_students = 54  # total number of students
    students_like_dance = 35  # number of students who like to dance
    students_like_badminton = 2  # number of students who like to play badminton

    # to find: number of students who like to paint

    # solution:
    # first, calculate the number of students who like to bake
    students_like_bake = 2 * students_like_badminton
    # next, calculate the number of students who like to paint
    students_like_paint = total_students - students_like_dance - students_like_badminton - students_like_bake
    return students_like_paint


Question: A farmer has 100 chickens and 15 cows. If he sells 20 chickens and buys 5 more cows, how many animals does he have now?

Answer:
def solution():
    # given:
    chickens_originally = 100  # number of chickens the farmer originally had
    cows_originally = 15  # number of cows the farmer originally had
    chickens_sold = 20  # number of chickens the farmer sold
    cows_bought = 5  # number of cows the farmer bought

    # to find: total number of animals the farmer has now

    # solution:
    # first, calculate the number of chickens the farmer has now
    chickens_now = chickens_originally - chickens_sold
    # next, calculate the number of cows the farmer has now
    cows_now = cows_originally + cows_bought
    # finally, calculate the total number of animals the farmer has now
    total_animals_now = chickens_now + cows_now
    return total_animals_now


Question: A library has 120 books. If 15 books are borrowed and 10 new books are added, how many books are in the library now?

Answer:
def solution():
    # given:
    books_originally = 120  # number of books the library originally had
    books_borrowed = 15  # number of books borrowed
    new_books_added = 10  # number of new books added

    # to find: number of books in the library now

    # solution:
    # first, calculate the number of books left after some were borrowed
    books_left = books_originally - books_borrowed
    # next, calculate the total number of books in the library now
    books_now = books_left + new_books_added
    return books_now


Question: A baker has 120 cupcakes. If he sells 30 cupcakes and makes 50 more, how many cupcakes does he have now?

Answer:
def solution():
    # given:
    cupcakes_originally = 120  # number of cupcakes the baker originally had
    cupcakes_sold = 30  # number of cupcakes the baker sold
    cupcakes_made = 50  # number of cupcakes the baker made

    # to find: number of cupcakes the baker has now

    # solution:
    # first, calculate the number of cupcakes left after some were sold
    cupcakes_left = cupcakes_originally - cupcakes_sold
    # next, calculate the total number of cupcakes the baker has now
    cupcakes_now = cupcakes_left + cupcakes_made
    return cupcakes_now


Question: A school has 500 students. If 200 students are in the morning shift and the rest are in the afternoon shift, how many students are in the afternoon shift?

Answer:
def solution():
    # given:
    total_students = 500  # total number of students in the school
    students_morning_shift = 200  # number of students in the morning shift

    # to find: number of students in the afternoon shift

    # solution:
    # calculate
Extracted answer: 13