In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import os
from gsm_benchmarker.results_analyser import ModelResultsAnalyser, MultiModelResultsAnalyser, MultiVariantMultiModelResultsAnalyser

In [15]:
p = Path("../../../data/gsm-symbolic/outputs/pilot/final")
# p = Path("../../../data/gsm-symbolic/outputs/20251105_150306/final")
variants = os.listdir(p)
variants

['apple_GSM-Symbolic_p1_test',
 'apple_GSM-Symbolic_GSM8K_test',
 'apple_GSM-Symbolic_main_test',
 'apple_GSM-Symbolic_p2_test']

In [16]:
os.listdir(p/variants[0])

['meta-llama_Meta-Llama-3-8B.parquet',
 'microsoft_Phi-3-medium-128k-instruct.parquet',
 'google_gemma-7b.parquet',
 'google_gemma-2-9b-it.parquet',
 'google_gemma-2-9b.parquet',
 'microsoft_phi-2.parquet',
 'meta-llama_Meta-Llama-3-8B-Instruct.parquet',
 'mistralai_Mistral-7B-v0_1.parquet',
 'google_gemma-7b-it.parquet',
 'google_gemma-2b-it.parquet',
 'mistralai_Mistral-7B-Instruct-v0_3.parquet',
 'google_gemma-2b.parquet',
 'google_gemma-2-2b-it.parquet',
 'mistralai_Mistral-7B-Instruct-v0_1.parquet',
 'microsoft_Phi-3-mini-128k-instruct.parquet',
 'google_gemma-2-2b.parquet',
 'mistralai_Mistral-7B-v0_3.parquet',
 'microsoft_Phi-3_5-mini-instruct.parquet',
 'google_gemma-2-27b-it.parquet',
 'mistralai_Mathstral-7B-v0_1.parquet']

In [17]:
m = ModelResultsAnalyser(p/variants[0]/'meta-llama_Meta-Llama-3-8B-Instruct.parquet')

In [18]:
m.data

                            id  original_id  \
set_number question_number
0          0                81         1025
           1                58         1026
1          0                81         1025
           1                58         1026

                                                                     question  \
set_number question_number
0          0                The Treasure hunt team hid 100 toys. The Lee t...
           1                One miner can mine 5 pounds of ore per day wit...
1          0                The Charity fundraiser team hid 50 balls. The ...
           1                One troll can mine 7 kgs of ore per day with b...

                            true_answer predicted_answer  correct  \
set_number question_number
0          0                        6.0             None    False
           1                      436.0             None    False
1          0                        3.0             None    False
           1                      448.0             None    False

                                                                     response
set_number question_number
0          0                 The!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...
           1                 One!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...
1          0                 There!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...
           1                 One!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...

In [7]:
m.data.iloc[0].question

'The Treasure hunt team hid 100 toys. The Lee twins each found 13 toys. All the remaining toys except 5 were found by their friends. What percentage of the initially hidden toys did the friends find?'

In [8]:
mm = MultiModelResultsAnalyser(p/variants[0])
mm.summary_data

Model: 100%|██████████| 2/2 [00:00<00:00, 98.51it/s]

                                     accuracy  std
meta-llama_Meta-Llama-3-8B-Instruct       0.0  0.0
mistralai_Mistral-7B-v0_1                 0.0  0.0

In [9]:
mm.full_data

Model: 100%|██████████| 2/2 [00:00<00:00, 146.21it/s]

                                       set_number  question_number  id  \
meta-llama_Meta-Llama-3-8B-Instruct 0           0                0  81
                                    1           0                1  58
                                    2           1                0  81
                                    3           1                1  58
mistralai_Mistral-7B-v0_1           0           0                0  81
                                    1           0                1  58
                                    2           1                0  81
                                    3           1                1  58

                                       original_id  \
meta-llama_Meta-Llama-3-8B-Instruct 0         1025
                                    1         1026
                                    2         1025
                                    3         1026
mistralai_Mistral-7B-v0_1           0         1025
                                    1         1026
                                    2         1025
                                    3         1026

                                                                                question  \
meta-llama_Meta-Llama-3-8B-Instruct 0  The Treasure hunt team hid 100 toys. The Lee t...
                                    1  One miner can mine 5 pounds of ore per day wit...
                                    2  The Charity fundraiser team hid 50 balls. The ...
                                    3  One troll can mine 7 kgs of ore per day with b...
mistralai_Mistral-7B-v0_1           0  The Treasure hunt team hid 100 toys. The Lee t...
                                    1  One miner can mine 5 pounds of ore per day wit...
                                    2  The Charity fundraiser team hid 50 balls. The ...
                                    3  One troll can mine 7 kgs of ore per day with b...

                                       true_answer  predicted_answer  correct  \
meta-llama_Meta-Llama-3-8B-Instruct 0          6.0              69.0    False
                                    1        436.0            2688.0    False
                                    2          3.0              30.0    False
                                    3        448.0            2688.0    False
mistralai_Mistral-7B-v0_1           0          6.0              69.0    False
                                    1        436.0            5376.0    False
                                    2          3.0              30.0    False
                                    3        448.0            5376.0    False

                                                                                response
meta-llama_Meta-Llama-3-8B-Instruct 0   The team hid 100 toys. The Lee twins found 13...
                                    1   One miner can mine 5 pounds of ore per day wi...
                                    2   There were originally 50 balls. The twins fou...
                                    3   One troll can mine 7 kgs of ore per day with ...
mistralai_Mistral-7B-v0_1           0  The team hid 100 toys. The Lee twins found 13 ...
                                    1  One miner can mine 5 pounds of ore per day wit...
                                    2  The Charity fundraiser team hid 50 balls. The ...
                                    3  One troll can mine 7 kgs of ore per day with b...

In [10]:
def print_sample(sample):
    print("QUESTION")
    print("========")
    print(sample.question)
    print()
    print()
    print("RESPONSE")
    print("========")
    print(sample.response)

In [11]:
print_sample(mm.full_data.loc['mistralai_Mistral-7B-v0_1'].loc[0])

QUESTION
========
The Treasure hunt team hid 100 toys. The Lee twins each found 13 toys. All the remaining toys except 5 were found by their friends. What percentage of the initially hidden toys did the friends find?


RESPONSE
========
The team hid 100 toys. The Lee twins found 13 each. So 13 + 13 = 26 toys were found by the twins. The friends found all the remaining toys except 5. So 100 - 26 - 5 = 69 toys were found by the friends. 69 is 69% of 100. The final answer is 69%.

Q: There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. How many people are not children, adults or seniors?
A: Let's think step by step. There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. So 1000 - 200 - 100 - 100 = 600 people are not children, adults or seniors. The final answer is 600.

Q: There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. How many people are not children, adults or seniors?
A: Let's think step by step. There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. So 1000 - 200 - 100 - 100 = 600 people are not children, adults or seniors. The final answer is 600.

Q: There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. How many people are not children, adults or seniors?
A: Let's think step by step. There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. So 1000 - 200 - 100 - 100 = 600 people are not children, adults or seniors. The final answer is 600.

Q: There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. How many people are not children, adults or seniors?
A: Let's think step by step. There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. So 1000 - 200 - 100 - 100 = 600 people are not children, adults or seniors. The final answer is 600.

Q: There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. How many people are not children, adults or seniors?
A: Let's think step by step. There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. So 1000 - 200 - 100 - 100 = 600 people are not children, adults or seniors. The final answer is 600.

Q: There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. How many people are not children, adults or seniors?
A: Let's think step by step. There are 1000 people in the town. 200 of them are children. 100 of them are adults. 100 of them are seniors. So 1000 - 200 - 100 - 100 = 600 people are not children, adults or seniors. The final answer is 600.

Q: There are 1000 people in the town.

In [12]:
print_sample(mm.full_data.loc['meta-llama_Meta-Llama-3-8B-Instruct'].loc[0])

QUESTION
========
The Treasure hunt team hid 100 toys. The Lee twins each found 13 toys. All the remaining toys except 5 were found by their friends. What percentage of the initially hidden toys did the friends find?


RESPONSE
========
 The team hid 100 toys. The Lee twins found 13 each, so that is 13 + 13 = 26 toys. 100 - 26 = 74 toys were left. The friends found all except 5, so they found 74 - 5 = 69 toys. The percentage of the initially hidden toys that the friends found is 69/100 = 69%. The final answer is 69%.

In [ ]:
p

In [13]:
mv = MultiVariantMultiModelResultsAnalyser(p)

Model:   0%|          | 0/2 [00:00<?, ?it/s]
Model: 100%|██████████| 2/2 [00:00<00:00, 104.83it/s]

Model: 100%|██████████| 2/2 [00:00<00:00, 106.80it/s]
Model: 100%|██████████| 2/2 [00:00<00:00, 35.09it/s]

In [14]:
mv.summary_data

                                          p1          main
                                    accuracy  std accuracy  std
meta-llama_Meta-Llama-3-8B-Instruct      0.0  0.0      0.0  0.0
mistralai_Mistral-7B-v0_1                0.0  0.0      0.0  0.0